### PR TITLE
quantified_code_fixes

### PR DESCRIPTION
**Pull request by the-zebulan**
I changed the instance methods to static methods and made two very minor PEP8 updates (2 blank lines above class definition and whitespace around `=` operator).

### CODE REVIEW

**Comment by the-zebulan** [comment]
I have also looked at fixing the other QuantifiedCode warning: `Use '@property` instead of Java-style setter/getter methods`

I was wondering what the name of the `get_sections` and `set_section` functions should be (after the change). Maybe just `sections` for both?

I could add it into the PR if you want, but I just wanted to make sure what to name the function first.

**Comment by cglewis** [comment]
@the-zebulan thanks!  yeah, i would just remove the get/set for both sections and options and just leave them as `section(s)` and `option(s)`

**Comment by cglewis** [comment]
also be sure and add yourself to `AUTHORS`

**Comment by the-zebulan** [comment]
@cglewis ,

Do you mean something like this?

```python
    @staticmethod
    def sections(s):
        return
    
    @staticmethod
    def options(s):
        return
```

I only ask because in the example from QuantifiedCode learn to fix, their example looks like this (with two functions with the same name and different decorators):

```python
class Person:
  def __init__(self, name):
    self._name = name

  @property
  def name(self):
    return self._name

  @name.setter
  def name(self, name):
    self._name = name
```

There just doesn't seem to be a `self.sections` or `self.options` variable in the `__init__` to get/set (yet?).

**Comment by cglewis** [comment]
ah, yeah, sorry about the confusion. correct there isn't an `__init__` yet, since none that has been implemented yet and is just stubs. by the `(s)` I was meaning plural/singular, so something like:

```
# implied getter, but since it's returning all of the sections, it's plural
@staticmethod
def sections():
    return

# implied setter, since it's only setting one section it's singular
@staticmethod
def section(section):
    return
```

Either way though, I could go both ways of either the above, or having it be the same name for both functions (in which case probably singular), so whichever way works for you.

**Comment by the-zebulan** [comment]
Thanks for clarifying that! Ok, I think since there will still be getters/setters I should probably use the `@property` decorators instead of `@staticmethod` though right? If the `sections` are going to come from a class variable like `self.sections` then you will need access to self (with `@staticmethod` you don't get access to `self`)?

I'll make another commit with the changes for you to see (and hopefully get rid of those last QualifiedCode issues!).

**Comment by the-zebulan** [comment]
With the first named `sections` and the second named `section`, I'm getting a message on PyCharm saying:

```
    @property
    def sections(self):
        return

    @sections.setter   # Names of function and decorator don't match
    def section(self, section):
        return
```

It goes away if both functions have the same name though.

**Comment by cglewis** [comment]
oh, good to know. make them the same name then I guess.

**Comment by the-zebulan** [comment]
Sorry, I went and switched them back to `@staticmethod` and that didn't get rid of the QuantifiedCode issues.

I'll try with the `@property` decorators as discussed. Sorry for taking so long!

**Comment by the-zebulan** [comment]
Maybe I should just stop now. When I look at the QuantifiedCode issues, it says to use `@staticmethod` but I already did on all those examples. I'm a bit confused.

What do you think? I don't fully understand what it is you are testing here, I don't know if making more changes is helping you guys or not...

**Comment by cglewis** [comment]
That is odd, maybe it will settle when it gets merged into master.  Otherwise looks good, thanks for helping out!

**Comment by the-zebulan** [comment]
@cglewis ,

Thanks for your time. It helps me to gain experience by submitting simple PR's.

**Pull request merged**
