### PR TITLE
Feature logging

### LINKED ISSUE #895: find all instances of try/except/pass and log the error
there are a number of places  in the code base that have something like:
```
try:
  // some code
except Exception as e:
  pass
```
Instead of just passing, it should instead log the error `e` (or whatever the variable is called in the exception).

### PR DESCRIPTION
**Pull request by 7Orion7**
Closes #895 . Added loggers and logging messages at all try/except/pass segments in the code.

### CODE REVIEW

**Comment by 7Orion7** [comment]
That should be all pass statements :)

**Comment by cglewis** [comment]
@7Orion7 looks good, but the two imports for the core tools (`rmq_es_connector` and `rq_worker`) need to have to their `requirements.txt` files updated to include `vent`

**Comment by 7Orion7** [comment]
hi @cglewis I am not exactly sure how to do this. Do I add your logging class into the requiremnts.txt?

**Comment by cglewis** [comment]
@7Orion7 since vent can be installed with pip, all you have to do is add `vent` in these two places: 

https://github.com/CyberReboot/vent/blob/master/vent/core/rmq_es_connector/requirements.txt
https://github.com/CyberReboot/vent/blob/master/vent/core/rq_worker/requirements.txt

that way when they import the vent logger it can find it.

**Pull request merged**
