### PR TITLE
Closes issue #438

### PR DESCRIPTION
**Pull request by cprafullchandra**

### CODE REVIEW

**Comment by cglewis** [comment]
note, tests are failing.

**Comment by cglewis** [comment]
this looks good, but still missing the use case of an invalid repo, without credentials. it prompts for a username and hangs there.

**Comment by cprafullchandra** [comment]
@cglewis I'm not able to reproduce. When I put an invalid repo in without credentials I get an error on the next screen and then upon clicking OK I return to main. Not getting a prompt for a username either. Are you providing a private repo?

**Comment by cprafullchandra** [comment]
@cglewis I do believe there actually is another bug with not checking for valid username password

**Comment by cglewis** [comment]
i had a really old version of git, after upgrading, the problem i was experiencing is gone.  for reference I was using git 2.3.0.

**Pull request merged**
