### PR TITLE
Added suggestion to add user to docker group

### LINKED ISSUE #900: vent primarily should be run without sudo to keep permissions clean, however the user needs to be in the docker group to execute docker commands
update the documentation to reflect that the user running vent needs to be in the `docker` group so that it can execute docker commands without `sudo`

### PR DESCRIPTION
**Pull request by sgaist**
Fixes #900

What is the alphabetical order of the AUTHORS file ? It's not really clear from a quick read.

### CODE REVIEW

**Comment by cglewis** [comment]
@sgaist it looks like a couple at the end of the AUTHORS file got added non-alphabetically.  It should be by name - do you mind fixing the order when you add yourself?

**Comment by sgaist** [comment]
Not at all. So ordered by first name ? That's what seems to be suggested by the first 7 entries.

**Comment by cglewis** [comment]
yeah, but first name. thanks!

**Comment by cglewis** [comment]
thanks!

**Pull request merged**
