### PR TITLE
Update vent.template

### PR DESCRIPTION
**Pull request by cominixo01**
Commenting locally_active based on #902

Be sure and add yourself to `AUTHORS` along with your changes.

### CODE REVIEW

**Comment by cglewis** [comment]
@cominixo01 please remove completely.  also there are multiple vent.template files in the project.

**Comment by cominixo01** [comment]
oh, i'm sorry, will do

**Comment by cominixo01** [comment]
Found those, don't know if there's more but probably not.

**Comment by cglewis** [comment]
@cominixo01 looks good now, thanks!  Just add yourself to the `AUTHORS` file and I'll merge.

**Comment by cominixo01** [comment]
Oh man, forgot to do that and deleted my fork before i saw your message, maybe i can add myself to AUTHORS with another pull request?

**Comment by cglewis** [comment]
@cominixo01 sure, no problem

**Comment by cominixo01** [comment]
Okay, thanks

**Pull request merged**
